Document: rocket
Title: Debian rocket Manual
Author: <insert document author here>
Abstract: This manual describes what rocket is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/rocket/rocket.sgml.gz

Format: postscript
Files: /usr/share/doc/rocket/rocket.ps.gz

Format: text
Files: /usr/share/doc/rocket/rocket.text.gz

Format: HTML
Index: /usr/share/doc/rocket/html/index.html
Files: /usr/share/doc/rocket/html/*.html
